# Options for analysis running.
run:
  go: '1.18'

linters-settings:
  varnamelen:
    ignore-names:
      - err
      - db
      - tx
      - w
      - r
      - m1
      - m2
  
  wsl:
    allow-separated-leading-comment: true
  
  gocritic:
      disabled-checks:
        - ifElseChain
  
  errcheck:
    exclude-functions: 
      - (net/http.ResponseWriter).Write
  
linters:
  # Enable all available linters.
  enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default-linters--e--enable
  disable:
    - wrapcheck
    - gci
    - ireturn
    - paralleltest
    - forcetypeassert
    - exhaustivestruct
    - exhaustruct
    - goerr113
    - errorlint
    - gochecknoglobals
    - gochecknoinits
    - tagliatelle
    - gofumpt
